# Generated by Django 5.0.10 on 2024-12-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0010_alter_ingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('tbsp', 'Tablespoon(s)'), ('cup', 'Cup(s)'), ('pint', 'Pint(s)'), ('stick', 'Stick'), ('floz', 'Fluid Ounce(s)'), ('gallon', 'Gallon(s)'), ('mL', 'Milliliter(s)'), ('lbs', 'Pound(s)'), ('not_set', 'None'), ('quart', 'Quart(s)'), ('amt', 'Amount'), ('g', 'Gram(s)'), ('tsp', 'Teaspoon(s)')], max_length=200, verbose_name='measurement'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('snack', 'Snack'), ('holiday', 'Holiday'), ('dessert', 'Dessert'), ('not_set', 'Not Set'), ('dinner', 'Dinner'), ('lunch', 'Lunch'), ('breakfast', 'Breakfast'), ('large_group', 'Large Groups/Parties')], default='not_set', max_length=20, verbose_name='recipe type'),
        ),
    ]
